# Generated by Django 4.2 on 2026-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='full_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
